version: '3'
services:
  aliyundriver:
    environment:
      REFRESH_TOKEN: '${REFRESH_TOKEN}'
      WEBDAV_AUTH_USER: '${WEBDAV_AUTH_USER}'
      WEBDAV_AUTH_PASSWORD: '${WEBDAV_AUTH_PASSWORD}'
    depends_on:
      - nginx
    image: messense/aliyundrive-webdav
    restart: always
    volumes:
      - './aliyundriver/aliyundrive-webdav:/etc/aliyundrive-webdav'
  adguardhome:
    depends_on:
      - nginx
    image: adguard/adguardhome:latest
    ports:
      - '53:53'
      - '53:53/udp'
      - '853:853'
    restart: always
    volumes:
      - './adguardhome/work:/opt/adguardhome/work'
      - './adguardhome/conf:/opt/adguardhome/conf'
  nginx:
    environment:
      TZ: '${TZ}'
    image: nginx:latest
    ports:
      - '8443:8443'
    restart: always
    volumes:
      - './nginx/templates:/etc/nginx/templates'
      - '/root/.acme.sh:/etc/nginx/.acme.sh'
  portainer:
    command: -H unix:///var/run/docker.sock
    depends_on:
      - nginx
    image: portainer/portainer-ce:latest
    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './portainer/data:/data'
  qinglong:
    depends_on:
      - nginx
    image: whyour/qinglong:latest
    restart: always
    volumes:
      - './qinglong/config:/ql/config'
      - './qinglong/log:/ql/log'
      - './qinglong/db:/ql/db'
      - './qinglong/repo:/ql/repo'
      - './qinglong/raw:/ql/raw'
      - './qinglong/scripts:/ql/scripts'
      - './qinglong/jbot:/ql/jbot'
      - './qinglong/ninja:/ql/ninja'
  transmission:
    depends_on:
      - nginx
    environment:
      TZ: '${TZ}'
      TRANSMISSION_WEB_HOME: '${TRANSMISSION_WEB_HOME}'
      USER: '${TRANSMISSION_USER}'
      PASS: '${TRANSMISSION_PASS}'
    image: ghcr.io/linuxserver/transmission:latest
    ports:
      - '51413:51413'
      - '51413:51413/udp'
    restart: always
    volumes:
      - ./transmission/config:/config
      - ./transmission/downloads:/downloads
      - ./transmission/watch:/watch

