version: '3'
services:
  aliyundriver:
    environment:
      TZ: '${TZ}'
      JAVA_OPTS: '${JAVA_OPTS}'
      ALIYUNDRIVE_REFRESH_TOKEN: '${ALIYUNDRIVE_REFRESH_TOKEN}'
      ALIYUNDRIVE_AUTH_PASSWORD: '${ALIYUNDRIVE_AUTH_PASSWORD}'
    depends_on:
      - nginx
      - rclone
    image: zx5253/webdav-aliyundriver
    restart: always
    volumes:
      - './aliyundriver/aliyun-driver:/etc/aliyun-driver'
  adguardhome:
    depends_on:
      - nginx
    image: 'adguard/adguardhome:latest'
    ports:
      - '53:53'
      - '853:853/tcp'
    restart: always
    volumes:
      - './adguardhome/work:/opt/adguardhome/work'
      - './adguardhome/conf:/opt/adguardhome/conf'
  nginx:
    environment:
      TZ: '${TZ}'
    image: 'nginx:latest'
    ports:
      - '8443:8443'
    restart: always
    volumes:
      - './nginx/templates:/etc/nginx/templates'
      - '/root/.acme.sh:/etc/nginx/.acme.sh'
  portainer:
    command: -H unix:///var/run/docker.sock
    depends_on:
      - nginx
    image: 'portainer/portainer-ce:latest'
    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './portainer/data:/data'
  qinglong:
    depends_on:
      - nginx
    image: 'whyour/qinglong:latest'
    restart: always
    volumes:
      - './qinglong/config:/ql/config'
      - './qinglong/log:/ql/log'
      - './qinglong/db:/ql/db'
      - './qinglong/repo:/ql/repo'
      - './qinglong/raw:/ql/raw'
      - './qinglong/scripts:/ql/scripts'
      - './qinglong/jbot:/ql/jbot'
      - './qinglong/ninja:/ql/ninja'
  rclone:
    command: mount aliyundriver:/ /data --vfs-cache-mode writes --allow-non-empty --allow-other
    devices:
      - /dev/fuse:/dev/fuse
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_ADMIN
    image: rclone/rclone:latest
    restart: always
    volumes:
      - './rclone/rclone:/config/rclone'
      - './rclone/data:/data:shared'

